// frontend/src/app/applyforleave/applyforleave.component.ts
import { Component, OnInit} from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-applyforleave',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './applyforleave.component.html',
  styleUrl: './applyforleave.component.css'
})
export class ApplyforleaveComponent {
  leaveType = '';
  startDate = '';
  endDate = '';
  reason = '';
  error = '';
  leaveBalance: any = {};
  userId = localStorage.getItem('user_id') || '1';

  constructor(private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    this.http.get<any>(`http://localhost:5000/leave_balance/${this.userId}`)
      .subscribe({
        next: (data) => this.leaveBalance = data,
        error: (err) => console.error('Error fetching leave balance:', err)
      });
  }

  onSubmit() {
    if (!this.leaveType || !this.startDate || !this.endDate || !this.reason) {
      this.error = 'Please fill all fields!';
      return;
    }

    const leaveData = {
      userId: this.userId,
      leavetype: this.leaveType,
      startdate: this.startDate,
      enddate: this.endDate,
      reason: this.reason
    };

    this.http.post<any>('http://localhost:5000/apply_leave', leaveData)
      .subscribe({
        next: (res) => {
          if (res.message === "Leave Request Submitted") {
            alert(`Leave request submitted for ${this.leaveType}. Pending approval.`);
            this.router.navigate(['/staff']);
          } else {
            alert(res.message);
          }
        },
        error: (err) => {
          console.error('Error submitting leave request:', err);
          alert('An error occurred while submitting your request.');
        }
      });
  }
}

<div class="leave-container">
    <h2>Apply For Leave</h2>
    <form (ngSubmit)="onSubmit()">
      <div>
        <label>Select Type of leave</label>
        <select [(ngModel)]="leaveType" name="leaveType" required>
          <option value="">--select--</option>
          <option value="casual">Casual Leave</option>
          <option value="sick">Sick Leave</option>
          <option value="earned">Earned Leave</option>
          <option value="unpaid">Unpaid</option>
        </select>
      </div>
  
      <div>
        <label>Select Start Date</label>
        <input type="date" [(ngModel)]="startDate" name="startDate" required />
      </div>
  
      <div>
        <label>Select End Date</label>
        <input type="date" [(ngModel)]="endDate" name="endDate" required />
      </div>
  
      <div>
        <label>Reason</label>
        <textarea [(ngModel)]="reason" name="reason" placeholder="Enter Your Reason" required></textarea>
      </div>
  
      <div *ngIf="error" style="color:red">{{ error }}</div>
  
      <button type="submit">Apply</button>
    </form>
  </div>

// leave-management/src/ApplyforLeave.jsx
import React,{useEffect, useState} from "react";
import "./ApplyforLeave.css";
import { useNavigate } from "react-router-dom";

function ApplyforLeave(){
    const[leavetype,setleavetype]=useState("");
    const[startdate,setstartdate]=useState("");
    const[enddate,setenddate]=useState("");
    const[reason,setreason]=useState("");
    const [error, setError] = useState("");
    const [leaveBalance, setLeaveBalance] = useState({});
    const navigate = useNavigate();
    
    const userId = localStorage.getItem("user_id") || 1;

   useEffect(()=>{
    fetch(`http://localhost:5000/leave_balance/${userId}`)
    .then((res) => {
      if (!res.ok) {
          throw new Error("Failed to fetch leave balance");
      }
      return res.json();
  })
    .then(data=>setLeaveBalance(data))
    .catch(err=>console.error("Error fetching leave balance:",err));
   },[userId]);

    function handleleavetype(e){
        setleavetype(e.target.value);
        }
    function handlestartdate(e){
        setstartdate(e.target.value);
    }
    function handleenddate(e){
        setenddate(e.target.value);
    }
    function handlereason(e){
        setreason(e.target.value);
    }
    function handlesubmit(e){
        e.preventDefault();

        if(!leavetype || !startdate || !enddate || !reason){
            setError("please fill all fields!");
            return;
        }

        if (leaveBalance[`${leavetype}_leave`] <= 0) {
          alert(`No leaves left for ${leavetype}. Cannot apply.`);
          return;
      }

        fetch("http://localhost:5000/apply_leave",{
          method:"POST",
          headers:{
            "Content-Type":"application/json"
          },
          body:JSON.stringify({
            userId:userId,
            leavetype:leavetype,
            startdate,
            enddate,
            reason
          })
        })
       .then(response=>response.json())
       .then(data=>{
        if(data.message==="Leave Request Submitted"){
          alert(`Leave request submitted for ${leavetype}. Pending approval.`);
          navigate("/staff");
        }else{
          alert(data.message);
        }
       }).catch(error=>console.error("Error submitting leave request:",error))
};

    

    
 return(
    <>
    <div className="leave-container">
        <h2>Apply For Leave</h2>
        <form onSubmit={handlesubmit}>
            <div>
              <label>Select Type of leave</label>
               <select value={leavetype} onChange={handleleavetype} required>
                <option value="">--select--</option>
                <option value="casual">casual leave </option>
                <option value="sick">sick leave</option>
                <option value="earned">earned</option>
                <option value="unpaid">Unpaid</option>
              </select> 
            </div>

            <div>
               <label>Select start date</label>
               <input type="date" value={startdate} onChange={handlestartdate} required />
            </div>

            <div>
              <label>Select End date</label>
              <input type="date" value={enddate} onChange={handleenddate} required />
            </div> 

            <div>
                <label>Reason</label>
                <textarea type="text" value={reason} placeholder="Enter Your Reason" onChange={handlereason} required />
            </div> 
           
            <button type="submit">Apply</button>
        </form>
    </div>
    </>
 );
}
export default ApplyforLeave
