// frontend/src/app/hodpage/hodpage.component.ts
import { Component,OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-hodpage',
  standalone:true,
  imports: [CommonModule],
  templateUrl: './hodpage.component.html',
  styleUrl: './hodpage.component.css'
})
export class HodpageComponent implements OnInit {
  leaveRequests: any[] = [];
  selectedRequest: any = null;
  hodName: string = '';
  activeTab: string = 'pending';

  constructor(private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    const storedHod = localStorage.getItem('name');
    if (storedHod) {
      this.hodName = storedHod;
    }

    this.fetchLeaveRequests(this.activeTab);
  }
  
  

//   get filteredRequests() {
//   if (this.activeTab === 'pending') {
//     return this.leaveRequests.filter(req => req.status === 'Pending');
//   } else if (this.activeTab === 'Approved/Rejected') {
//     return this.leaveRequests.filter(req => req.status === 'Approved' || req.status === 'Rejected');
//   } else {
//     return this.leaveRequests; // history = all
//   }
// }

changeTab(tab: string) {
  this.activeTab = tab;
  this.fetchLeaveRequests(tab);
} 

get activeTabTitle() {
  switch (this.activeTab) {
    case 'pending': return 'Pending Requests';
    case 'Approved/Rejected': return 'Approved/Rejected';
    case 'history': return 'Request History';
    default: return '';
  }
} 

  fetchLeaveRequests(tab: string) {
    let url = 'http://localhost:5000/leave_requests';

    if (tab === 'Approved/Rejected') {
      url = 'http://localhost:5000/approved-rejected';
    } else if (tab === 'history') {
      url = 'http://localhost:5000/leave-history';
    }

    this.http.get<any[]>(url).subscribe({
      next: (data) => this.leaveRequests = data,
      error: (err) => console.error('Error fetching leave requests:', err)
    });
  }

  handleLogout() {
    localStorage.removeItem('hodtoken');
    localStorage.removeItem('name');
    this.router.navigate(['/']);
  }

  async handleReqClick(request: any) {
    try {
      const response: any = await this.http.get(`http://localhost:5000/leave_requests/${request.id}`).toPromise();
      this.selectedRequest = { ...request, ...response };
    } catch (error) {
      console.error('Error fetching leave details:', error);
    }
  }

  closeModel() {
    this.selectedRequest = null;
  }

  handleLeaveAction(request: any, status: string) {
    if (!request) return;

    this.http.put(`http://localhost:5000/update_leaves_status/${request.id}`, {
      status: status,
      userId: request.user_id,
      leavetype: request.leave_type
    }).subscribe({
      next: () => {
        this.leaveRequests = this.leaveRequests.map(req =>
          req.id === request.id ? { ...req, status: status } : req
        );
        this.closeModel();
      },
      error: (err) => console.error('Error updating leave request:', err)
    });
  }
}


<div class="hod-container">
    <div class="logout">
      <button class="logout-btn" (click)="handleLogout()">Logout</button>
    </div>
  
    <div class="navbar">
      <header class="staff-header">HOD Dashboard</header>
      <h2>Welcome, {{ hodName || 'HOD' }}</h2>
    </div>
    <div><div class="hod-tabs">
        <button [class.active]="activeTab === 'pending'" (click)="changeTab('pending')">Pending</button>
        <button [class.active]="activeTab === 'Approved/Rejected'" (click)="changeTab('Approved/Rejected')">Approved/Rejected</button>
        <button [class.active]="activeTab === 'history'" (click)="changeTab('history')">History</button>
      </div></div>
    <div class="main-content">
        
      <div class="pending-box">
        <h3>{{ activeTabTitle }}</h3>
        <div class="req-list">
            <div *ngIf="leaveRequests.length > 0; else noRequests">
                <div *ngFor="let request of leaveRequests" class="request-item">
              
              <p><strong>{{ request.name }}</strong> - {{ request.reason }}</p>
              <p><strong>Status:</strong> {{ request.status }}</p>
              <p>
                <strong>Dates:</strong>
                {{ request.start_date | date: 'longDate' }} to
                {{ request.end_date | date: 'longDate' }}
              </p>
              <div class="action-btns" *ngIf="activeTab==='pending'">
                <button class="accept" (click)="handleLeaveAction(request, 'Approved')">Accept</button>
                <button class="reject" (click)="handleLeaveAction(request, 'Rejected')">Decline</button>
              </div>
            </div>
          </div>
          <ng-template #noRequests>
            <p>No requests</p>
          </ng-template>
        </div>
      </div>
    </div>
  
    <footer class="hod-footer">
      S+R <br />
      © 2024 Schopper Riegler - All Rights Reserved.
    </footer>
  </div>

// leave-management/src/HodPage.jsx
import React,{useEffect, useState} from "react";
import './HodPage.css';
import { Navigate } from "react-router-dom";
import { useNavigate } from "react-router-dom";

function HodPage(){
    const navigate = useNavigate();

    const [leavereq,setleavereq]=useState([]);
    const [selectedRequest, setSelectedRequest] = useState(null);
    const [hodName, setHodName] = useState("");

    useEffect(() => {
        
        const storedHod = localStorage.getItem("name"); 
        if (storedHod) {
            setHodName(storedHod);
        }
    }, []);
    useEffect(() => {
       const FetchLeaveRequests =async () =>{
        try {
            const response= await fetch("http://localhost:5000/leave_requests");
            if(!response.ok) throw new Error("failed to fetch");

            const data= await response.json();
            setleavereq(data);
        }catch(error){
            console.error("error fetching data",error);
        }
       };
       FetchLeaveRequests();
    }, []);
    const handlelogout=()=>{
        localStorage.removeItem("hodtoken");
        localStorage.removeItem("hodName");
        navigate("/");
    }
    const handleReqClick = async (request) => {
       try{
        const response= await fetch(`http://localhost:5000/leave_requests/${request.id}`);
        if(!response.ok) throw new Error("failed to fetch");

        const data=await response.json();
        console.log("fetched data",data);
        setSelectedRequest({...request,...data});

       }catch(error){
        console.error("error fetching leave details:",error);
       }
    };
    useEffect(() => {
        console.log("Updated selectedRequest:", selectedRequest);
     }, [selectedRequest]);
    function closemodel(){
        setSelectedRequest(null);
    }
    const handleleaveaction = async (request,status) =>{
        if(!request) return;

        try{
            const response=await fetch(`http://localhost:5000/update_leaves_status/${request.id}`,
                {
                    method:"PUT",
                    headers: {"Content-Type" : "application/json"},
                    body: JSON.stringify({status,
                        userId:request.user_id,
                        leavetype:request.leave_type,
                    }),
                });
          if(!response.ok) throw new Error("failed to upadte status");
          
          setleavereq((prev)=>
            prev.map((req)=>(req.id===request.id ?{...req,status: status}:req))
        );
        closemodel();
    }catch(error){
        console.error("error updating leave requests",error);
    }};
  
    return( <>
<div className="hod-container">
<div className="logout"><button className="logout-btn" onClick={handlelogout}>Logout</button></div>
    <div className="navbar">
    <header className="staff-header">HOD Dashboard</header>
    <h2>Welcome, {hodName ? hodName : "HOD"}</h2>
   
        </div>
           <div className="main-content">
             <div className="pending-box">
             <h3>Pending Requests</h3>
            <div className="req-list">
                  {leavereq.length > 0 ? (
                  leavereq.map((request, index) => (
                    <div key={index} className="request-item">
                  <p>
                    <strong>{request.name}</strong> - {request.reason}
                  </p>
                  <p>
                    <strong>Status:</strong> {request.status}
                  </p>
                  <p>
                  <strong>Dates:</strong> {new Date(request.start_date).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric"
                    })} {" "}
                 <strong>to</strong>{" "}
                {new Date(request.end_date).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric"
                   })}
                  </p>
                  <div className="action-btns">
                    <button
                      className="accept"
                      onClick={() => handleleaveaction(request, "Approved")}
                    >
                      Accept
                    </button>

                    <button
                      className="reject"
                      onClick={() => handleleaveaction(request, "Rejected")}
                    >
                      Decline
                    </button>
                  </div>
                </div>
              ))
            ) : (
              <p>No pending requests</p>
            )}
          </div>
        </div>
      </div>
      <footer className="hod-footer">
        S+R <br/>
        &copy; 2024 Schopper Riegler - All Rights Reserved.
      </footer>
    </div>
  </>);
};
export default HodPage
